version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.2
  circle-compare-url: iynere/compare-url@0.1.10
  kube-orb: sandbox/kubernates@dev:alpha


executors:
  cli:
    docker:
      - image: circleci/circleci-cli
  lint-condo:
    docker:
      - image: singapore/lint-condo
  ci-base:
    docker:
      - image: cibuilds/base

jobs:
  lint:
    executor: lint-condo
    steps:
      - checkout
      - run: yamllint .

  validate:
    executor: cli
    steps:
      - checkout

      - orb-tools/pack:
          source: src
          destination: orb.yml

      - run: circleci orb validate orb.yml

      - persist_to_workspace:
          root: .
          paths:
            - orb.yml

  publish-dev:
    executor: cli
    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run: |
          circleci orb publish workspace/orb.yml sandbox/kubernetes@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN
          circleci orb publish workspace/orb.yml sandbox/kubernetes@dev:alpha --token $CIRCLE_TOKEN

  trigger-integration:
    executor: ci-base
    steps:
      - checkout

      - run: |
          INTEGRATION_TAG=integration-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
          git tag $INTEGRATION_TAG
          git push origin $INTEGRATION_TAG

  integration-test:
    executor: ci-base
    steps:
      - checkout
      - run: echo "test"
      - kube-orb/install

  dev-promote-prod:
    executor: cli
    steps:
      - checkout
      - run: echo "hello"

workflows:
  version: 2
  build_unit-test_dev-deploy:
    jobs:
      - lint

      - validate:
          requires:
            - lint

      - publish-dev:
          requires:
            - validate
          context: orb-publishing

      - trigger-integration:
          requires:
            - publish-dev

  integration-test_prod-deploy:
    jobs:
      - integration-test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /integration-*/

      - dev-promote-prod:
          requires:
            - integration-test
          filters:
            branches:
              only: master
            tags:
              only: /integration-*/
          context: orb-publishing
