description: Install kubeconfig file

parameters:
  kubeconfig:
    type: string
    default: base64 encoded kubconfig file

steps:
  - run:
      name: Install kubeconfig
      command: |
        if [[ -n <<parameters.kubeconfig>> ]]; then
          echo -n <<parameters.kubeconfig>> | base64 -d > $HOME/.kube/config
        fi
