description: Install kubeconfig file

parameters:
  kubeconfig:
    type: env_var_name
    description: Environment variable name containing base64 encoded kubeconfig file
    default: KUBECONFIG

steps:
  - run:
      name: Install kubeconfig
      command: |
        if [ -n "${<<parameters.kubeconfig>>}" ]; then
          mkdir -p $HOME/.kube
          echo -n "${<<parameters.kubeconfig>>}" | base64 -d > $HOME/.kube/config
        fi
